import Head from "next/head";
import Image from "next/image";
import Script from "next/script";

import "@govbr-ds/core/dist/core.min.css";
import { useEffect } from "react";

export default function MainLayout({
  children,
}: {
  children: React.ReactElement | React.ReactElement[];
}) {
  const title = process.env.NEXT_PUBLIC_SITE_NAME || "Next GovBR-DS";
  const description = "Generated by create next app";

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="{description}" />
      </Head>
      {children}
    </>
  );
}
